### PR TITLE
support for scaffoldBB style

### PR DESCRIPTION
**Pull request by MannixMD**

### CODE REVIEW

**Comment by Crizz0** [comment]
Hi,

thank you for your PR.

Could you explain to me, why this is needed? Usually all styles should inherit the templates from prosilver. More template-file increase the maintaining effort on my side. 

Could this be done only via a CSS addition?

**Comment by MannixMD** [comment]
This style doesn't inherit from prosilver and it's build on bootstrap so this changes are needed. You can deny the pr if don't want to bother with maintainability i will keep these changes here and on my site. Cheers ;)

**Comment by gn36** [comment]
I would propose to put these style changes into a separate custom extension then. As long as the other extension is installed, it shouldn't  matter whether the style is inside a different extension and the extension should be as simple as just a collection of style files at the correct paths.

**Comment by gn36** [comment]
But maybe I am wrong and it has the extension path somewhere in the filenames when they get loaded... Then it will get more tricky and you have to override style files in the other extension. Not sure how that works.

**Pull request closed without merging**
